# SQL Mini Project

Database Used : [Chinook open source database](https://github.com/lerocha/chinook-database)
![](https://www.datameer.com/wp-content/uploads/2020/12/SQL-FAQ-Feat-924x512.png)


#### The idea behind this project is to showcase the usage of SQL to retrieve data from the databases and then using it for analysis .We will be able to apply various SQL queries and functions and then gather useful insights from it about our data. 

##### We will do this by following a 'Questions and Answers' approach asking and then answering various questions. 

## How to Run the Code


**Option 1: Running using free online resources (1-click, recommended):** The easiest way to start executing the code is to click the **Run** button at the top of this page and select **Run on Binder**. This will set up a cloud-based Jupyter notebook server and allow you to modify/execute the code.


**Option 2: Running on your computer locally:** To run the code on your computer locally, you'll need to set up [Python](https://www.python.org), download the notebook and install the required libraries. Click the **Run** button at the top of this page, select the **Run Locally** option, and follow the instructions.

## SQLite and Initial Setup

Relational databases generally have two components:

1. **Database Server/Engine**: A software package that manages databases and runs in the background, listening for SQL queries from authorized users E.g. MySQL server, Microsoft SQL server, Postgres etc.
2. **Database Client**: A command-line tool or graphical user interface (GUI) to connect to the database server and run SQL queries. E.g. MySQL workbench, PgAdmin etc.

The server and client can be on the same computer e.g. both on your laptop, or on different computers e.g. the database server can be running on the cloud and you can connect to it using a client installed on your computer.

Most database servers/engines are designed to operate on databases containing large amounts of data (e.g. 100s of GBs) and to handle a very high volume of queries (e.g. thousands of queries per second). They typically require powerful hardware i.e. multi-core CPUs and large amounts of RAM.


<img src="https://www.sqlite.org/images/sqlite370_banner.gif" width="240" style="margin-left:0">

In this project, however, we'll use a lightweight database engine called [SQLite](https://www.sqlite.org/index.html), which is well-suited for databases with small amounts of data and has very limited CPU & RAM requirements. Despite being limited in its capabilities, it is the [most widely used database engine in the world](https://www.sqlite.org/mostdeployed.html). SQLite is used by smartphone apps, web browsers, desktop applications, IoT devices etc. to store and manage data locally on the device. 

If you're running this locally, you'll need to [download and install `sqlite3`](https://www.servermania.com/kb/articles/install-sqlite/) on your computer. `sqlite3` is already installed on Binder. You can verify that you have `sqlite3` installed by running the following command to show the version of SQLite you have installed:

In [4]:
!sqlite3 --version

3.36.0 2021-06-18 18:36:39 5c9a6c06871cb9fe42814af9c039eb6da5427a6ec28f187af7ebfb62eafa66e5


Unlike other relational databases, SQLite doesn't have separate server and client packages. The `sqlite3` command line tool is all your need to create and interact with SQLite databases. The databases themselves are stored as files with the extension `.sqlite`. You can perform CRUD operations on the database simply by passing SQL queries using `sqlite3`.

Here's a visual representation of how SQLite differs from other relational database servers ([source](https://devopedia.org/sqlite)):

<img src="https://i.imgur.com/eC5Ieni.png" width="640">


Note that a `.sqlite` file is different from a `.sql` file, which contains commands for creating tables and inserting data. The `.sqlite` file is the actual database where the data is stored in a binary tabular format for efficient querying and manipulation.

In this project, we'll use the [Chinook open source database](https://github.com/lerocha/chinook-database). Let's begin by downloading the `.sqlite` file for the database containing all the required tables and the sample data. 

In [5]:
from urllib.request import urlretrieve

In [6]:
db_url = 'https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite'

In [7]:
urlretrieve(db_url, 'chinook.sqlite')

('chinook.sqlite', <http.client.HTTPMessage at 0x7f56fe0e6fd0>)

The database `chinook.sqlite` is now downloaded. To access and interact with the database by writing SQL queries directly within Jupyter, we'll use the [`ipython-sql`](https://pypi.org/project/ipython-sql/) library that provides the `%%sql` magic commands. It uses the [`sqlalchemy`](https://sqlalchemy.org) library behind the scenes to interact with the database.

In [8]:
!pip install sqlalchemy ipython-sql --quiet --upgrade

In [9]:
%load_ext sql

We can now connect to the database using a [SQLAlchemy connection string](https://docs.sqlalchemy.org/en/14/core/engines.html). We'll use the `%%sql` Jupyter magic command.

In [10]:
%%sql 

sqlite:///chinook.sqlite

We are now connected to the database and we can start writing SQL queries.

## Chinook Database Structure and Queries

The Chinook data model represents a digital media store, including tables for artists, albums, media tracks, invoices and customers.

The Chinook database represents a digital media store, including tables for artists, albums, media tracks, invoices and customers. Here's an [Entity Relationship Diagram](https://www.guru99.com/er-diagram-tutorial-dbms.html) (ERD) showing the structure of the Chinook database:

![](https://i.imgur.com/X1wM142.png)

#####  Let's begin by looking at the data from some of the tables in the database :

We can write SQL queries directly within Jupyter code cells by including the magic command `%%sql` as the first line of the cell, indicating that contents of cell represent a SQL query.

1. Table `Artist` :

In [14]:
%%sql 

SELECT * FROM Artist LIMIT 5   /*LIMIT is used to select the number of rows we want to display*/

 * sqlite:///chinook.sqlite
Done.


[(1, 'AC/DC'),
 (2, 'Accept'),
 (3, 'Aerosmith'),
 (4, 'Alanis Morissette'),
 (5, 'Alice In Chains')]

2. Table `Album`

In [15]:
%%sql 

SELECT * FROM Album LIMIT 5

 * sqlite:///chinook.sqlite
Done.


[(1, 'For Those About To Rock We Salute You', 1),
 (2, 'Balls to the Wall', 2),
 (3, 'Restless and Wild', 2),
 (4, 'Let There Be Rock', 1),
 (5, 'Big Ones', 3)]

## Selection and Ordering

Here, we will use SQL to use its selection and ordering queries : 

> **QUESTION 1**: Write a SQL query to sort the rows from the table `Track` in alphabetical order of Track name and display the first 10 rows?

In [ ]:
%%sql

SELECT * FROM `Track` ORDER BY `Name` LIMIT 10 ;

> **QUESTION 2**: Write a SQL query to show the _next 10_ rows based on the above criteria.

In [24]:
%%sql

SELECT * FROM `Track` ORDER BY `Name` LIMIT 10 OFFSET 10 ;  -- OFFSET is used to skip a certain number of rows and then display the results

 * sqlite:///chinook.sqlite
Done.


[(3471, '(There Is) No Greater Love (Teo Licks)', 322, 2, 9, 'Isham Jones & Marty Symes', 167933, 2773507, 0.99),
 (1947, '(We Are) The Road Crew', 160, 1, 3, 'Clarke/Kilmister/Taylor', 192600, 6283035, 0.99),
 (2595, '(White Man) In Hammersmith Palais', 211, 1, 4, 'Joe Strummer/Mick Jones', 240640, 7883532, 0.99),
 (709, '(Wish I Could) Hideaway', 55, 1, 1, 'J.C. Fogerty', 228466, 7432978, 0.99),
 (2869, '...And Found', 231, 3, 19, None, 2563833, 500330548, 1.99),
 (1894, '...And Justice For All', 156, 1, 3, 'James Hetfield, Lars Ulrich & Kirk Hammett', 585769, 19262088, 0.99),
 (2906, '...In Translation', 230, 3, 19, None, 2604575, 215441983, 1.99),
 (3166, '.07%', 228, 3, 21, None, 2585794, 541715199, 1.99),
 (1268, '01 - Prowler', 100, 1, 6, 'Steve Harris', 236173, 5668992, 0.99),
 (1269, '02 - Sanctuary', 100, 1, 6, "David Murray/Paul Di'Anno/Steve Harris", 196284, 4712576, 0.99)]

> **QUESTION 3**: Write some SQL queries in the cells below to explore the first few rows of each table in the database.

In [25]:
%%sql

SELECT * FROM `employee` LIMIT 10;  -- First 10 rows for Table `Employee`

 * sqlite:///chinook.sqlite
Done.


[(1, 'Adams', 'Andrew', 'General Manager', None, '1962-02-18 00:00:00', '2002-08-14 00:00:00', '11120 Jasper Ave NW', 'Edmonton', 'AB', 'Canada', 'T5K 2N1', '+1 (780) 428-9482', '+1 (780) 428-3457', 'andrew@chinookcorp.com'),
 (2, 'Edwards', 'Nancy', 'Sales Manager', 1, '1958-12-08 00:00:00', '2002-05-01 00:00:00', '825 8 Ave SW', 'Calgary', 'AB', 'Canada', 'T2P 2T3', '+1 (403) 262-3443', '+1 (403) 262-3322', 'nancy@chinookcorp.com'),
 (3, 'Peacock', 'Jane', 'Sales Support Agent', 2, '1973-08-29 00:00:00', '2002-04-01 00:00:00', '1111 6 Ave SW', 'Calgary', 'AB', 'Canada', 'T2P 5M5', '+1 (403) 262-3443', '+1 (403) 262-6712', 'jane@chinookcorp.com'),
 (4, 'Park', 'Margaret', 'Sales Support Agent', 2, '1947-09-19 00:00:00', '2003-05-03 00:00:00', '683 10 Street SW', 'Calgary', 'AB', 'Canada', 'T2P 5G3', '+1 (403) 263-4423', '+1 (403) 263-4289', 'margaret@chinookcorp.com'),
 (5, 'Johnson', 'Steve', 'Sales Support Agent', 2, '1965-03-03 00:00:00', '2003-10-17 00:00:00', '7727B 41 Ave', 'Calgary', 'AB', 'Canada', 'T3B 1Y7', '1 (780) 836-9987', '1 (780) 836-9543', 'steve@chinookcorp.com'),
 (6, 'Mitchell', 'Michael', 'IT Manager', 1, '1973-07-01 00:00:00', '2003-10-17 00:00:00', '5827 Bowness Road NW', 'Calgary', 'AB', 'Canada', 'T3B 0C5', '+1 (403) 246-9887', '+1 (403) 246-9899', 'michael@chinookcorp.com'),
 (7, 'King', 'Robert', 'IT Staff', 6, '1970-05-29 00:00:00', '2004-01-02 00:00:00', '590 Columbia Boulevard West', 'Lethbridge', 'AB', 'Canada', 'T1K 5N8', '+1 (403) 456-9986', '+1 (403) 456-8485', 'robert@chinookcorp.com'),
 (8, 'Callahan', 'Laura', 'IT Staff', 6, '1968-01-09 00:00:00', '2004-03-04 00:00:00', '923 7 ST NW', 'Lethbridge', 'AB', 'Canada', 'T1H 1Y8', '+1 (403) 467-3351', '+1 (403) 467-8772', 'laura@chinookcorp.com')]

In [26]:
%%sql

SELECT * FROM `customer` LIMIT 10;  -- -- First 10 rows for Table `Customer`

 * sqlite:///chinook.sqlite
Done.


[(1, 'Luís', 'Gonçalves', 'Embraer - Empresa Brasileira de Aeronáutica S.A.', 'Av. Brigadeiro Faria Lima, 2170', 'São José dos Campos', 'SP', 'Brazil', '12227-000', '+55 (12) 3923-5555', '+55 (12) 3923-5566', 'luisg@embraer.com.br', 3),
 (2, 'Leonie', 'Köhler', None, 'Theodor-Heuss-Straße 34', 'Stuttgart', None, 'Germany', '70174', '+49 0711 2842222', None, 'leonekohler@surfeu.de', 5),
 (3, 'François', 'Tremblay', None, '1498 rue Bélanger', 'Montréal', 'QC', 'Canada', 'H2G 1A7', '+1 (514) 721-4711', None, 'ftremblay@gmail.com', 3),
 (4, 'Bjørn', 'Hansen', None, 'Ullevålsveien 14', 'Oslo', None, 'Norway', '0171', '+47 22 44 22 22', None, 'bjorn.hansen@yahoo.no', 4),
 (5, 'František', 'Wichterlová', 'JetBrains s.r.o.', 'Klanova 9/506', 'Prague', None, 'Czech Republic', '14700', '+420 2 4172 5555', '+420 2 4172 5555', 'frantisekw@jetbrains.com', 4),
 (6, 'Helena', 'Holý', None, 'Rilská 3174/6', 'Prague', None, 'Czech Republic', '14300', '+420 2 4177 0449', None, 'hholy@gmail.com', 5),
 (7, 'Astrid', 'Gruber', None, 'Rotenturmstraße 4, 1010 Innere Stadt', 'Vienne', None, 'Austria', '1010', '+43 01 5134505', None, 'astrid.gruber@apple.at', 5),
 (8, 'Daan', 'Peeters', None, 'Grétrystraat 63', 'Brussels', None, 'Belgium', '1000', '+32 02 219 03 03', None, 'daan_peeters@apple.be', 4),
 (9, 'Kara', 'Nielsen', None, 'Sønder Boulevard 51', 'Copenhagen', None, 'Denmark', '1720', '+453 3331 9991', None, 'kara.nielsen@jubii.dk', 4),
 (10, 'Eduardo', 'Martins', 'Woodstock Discos', 'Rua Dr. Falcão Filho, 155', 'São Paulo', 'SP', 'Brazil', '01007-010', '+55 (11) 3033-5446', '+55 (11) 3033-4564', 'eduardo@woodstock.com.br', 4)]

In [27]:
%%sql

SELECT * FROM `invoiceline` LIMIT 5;  -- First 5 rows for Table `InvoiceLine`

 * sqlite:///chinook.sqlite
Done.


[(1, 1, 2, 0.99, 1),
 (2, 1, 4, 0.99, 1),
 (3, 2, 6, 0.99, 1),
 (4, 2, 8, 0.99, 1),
 (5, 2, 10, 0.99, 1)]

## Counting

Here, we will use SQL to use its `COUNT` function :
> **QUESTION 4**: Write a SQL query to calculate the total number of employees working at Chinook.

In [30]:
%%sql

SELECT count(*) FROM employee;  -- '*' is an equivalent of 'All' in SQL. The query here denotes counting all the rows that we have in the employee table

 * sqlite:///chinook.sqlite
Done.


[(8,)]

> **QUESTION 5**: Write SQL queries to calculate the total number customers, total number of artists and total number of tracks in the database.

In [34]:
%%sql

SELECT DISTINCT COUNT(customerid) from customer ;  -- `DISTINCT COUNT` gives the count for unique values

 * sqlite:///chinook.sqlite
Done.


[(59,)]

In [35]:
%%sql

SELECT DISTINCT COUNT(artistid) from artist ;

 * sqlite:///chinook.sqlite
Done.


[(275,)]

In [36]:
%%sql
SELECT DISTINCT COUNT(trackid) from track ;

 * sqlite:///chinook.sqlite
Done.


[(3503,)]

Let's save our work before continuing.

## Aggregation and Grouping

Here, we will get slightly advanced and use Aggregation and Grouping features from SQL .
> **QUESTION 6**: Write a SQL query to show the top 10 albums with the highest number of tracks. 
The result should contain 2 columns: album ID and number of tracks in the album (Let the name of column be "Tracks").

In [39]:
%%sql

SELECT `albumid`,
    count(`trackid`) as `Tracks` 
    from `track` 
    GROUP BY `albumid` ORDER BY Tracks DESC LIMIT 10;    -- `Groupby` is used to group the data and `OrderBy` is used to arrange the data in a particular order.

 * sqlite:///chinook.sqlite
Done.


[(141, 57),
 (23, 34),
 (73, 30),
 (229, 26),
 (230, 25),
 (251, 25),
 (83, 24),
 (231, 24),
 (253, 24),
 (24, 23)]

> **QUESTION 7**: Improve the above query to also show the album name, artist ID and artist name .

In [41]:
%%sql 
SELECT track.albumid,
    count(`trackid`) as `Tracks`,
    album.title, album.artistid, artist.name as `Artist Name`
    from `track` JOIN `album` on track.albumid = album.albumid
    JOIN `artist` on album.artistid = artist.artistid
    GROUP BY track.albumid ORDER BY Tracks DESC LIMIT 10;

 * sqlite:///chinook.sqlite
Done.


[(141, 57, 'Greatest Hits', 100, 'Lenny Kravitz'),
 (23, 34, 'Minha Historia', 17, 'Chico Buarque'),
 (73, 30, 'Unplugged', 81, 'Eric Clapton'),
 (229, 26, 'Lost, Season 3', 149, 'Lost'),
 (230, 25, 'Lost, Season 1', 149, 'Lost'),
 (251, 25, 'The Office, Season 3', 156, 'The Office'),
 (83, 24, 'My Way: The Best Of Frank Sinatra [Disc 1]', 85, 'Frank Sinatra'),
 (231, 24, 'Lost, Season 2', 149, 'Lost'),
 (253, 24, 'Battlestar Galactica (Classic), Season 1', 158, 'Battlestar Galactica (Classic)'),
 (24, 23, 'Afrociberdelia', 18, 'Chico Science & Nação Zumbi')]

> **QUESTION 8** List the top 10 albums with the highest number of tracks.

In [66]:
%%sql
SELECT album.title as `Album Name`, album.albumid, count(trackid) as `No. of Tracks`
    from album JOIN track ON track.albumid = album.albumid
    join artist ON album.artistid = artist.artistid
    GROUP BY `Album Name` ORDER BY `No. of Tracks` DESC LIMIT 10 ;

 * sqlite:///chinook.sqlite
Done.


[('Greatest Hits', 141, 57),
 ('Minha Historia', 23, 34),
 ('Unplugged', 73, 30),
 ('Lost, Season 3', 229, 26),
 ('The Office, Season 3', 251, 25),
 ('Lost, Season 1', 230, 25),
 ('My Way: The Best Of Frank Sinatra [Disc 1]', 83, 24),
 ('Lost, Season 2', 231, 24),
 ('Battlestar Galactica (Classic), Season 1', 253, 24),
 ('Instant Karma: The Amnesty International Campaign to Save Darfur', 255, 23)]

> **QUESTION 9** List the top 10 artists with the highest number of tracks.

In [46]:
%%sql
SELECT artist.name as ArtistName, count(trackid) as tracks
    from track JOIN album ON track.albumid = album.albumid
    join artist ON album.artistid = artist.artistid
    GROUP BY artistname ORDER BY tracks DESC LIMIT 10 ;

 * sqlite:///chinook.sqlite
Done.


[('Iron Maiden', 213),
 ('U2', 135),
 ('Led Zeppelin', 114),
 ('Metallica', 112),
 ('Lost', 92),
 ('Deep Purple', 92),
 ('Pearl Jam', 67),
 ('Lenny Kravitz', 57),
 ('Various Artists', 56),
 ('The Office', 53)]

Let's save our work before continuing.

## Functions and Joins

Here, we will explore the SQL Functions and different types of `JOINS` that if offers :


> **QUESTION 10**: Show a list of the top 10 customer with the highest total spend in 2012. 
-Calculate the total amount spent by each customer by adding the totals from all their invoices in the year 2012. -Order the list by the invoice total (decreasing order). 
-The result should contain the rows CustomerId, FirstName, LastName and TotalSpend. 

Now,  SQLite doesn't support the `YEAR` function. So, we will Instead use `strftime("%Y", Invoice.InvoiceDate)` to extract the year from the column `InvoiceDate` as a string.

In [71]:
%%sql

select customer.customerid, firstname, lastname,
    sum(total) as `Total Spend`
    from customer JOIN invoice ON customer.customerid = invoice.customerid
    where strftime('%Y',invoicedate) = "2012"
    GROUP BY customer.customerid ORDER BY `Total Spend` DESC LIMIT 10; 

 * sqlite:///chinook.sqlite
Done.


[(26, 'Richard', 'Cunningham', 25.84),
 (34, 'João', 'Fernandes', 24.77),
 (13, 'Fernanda', 'Ramos', 24.75),
 (51, 'Joakim', 'Johansson', 24.75),
 (55, 'Mark', 'Taylor', 22.77),
 (5, 'František', 'Wichterlová', 18.84),
 (43, 'Isabelle', 'Mercier', 18.84),
 (28, 'Julia', 'Barnett', 17.88),
 (22, 'Heather', 'Leacock', 17.84),
 (24, 'Frank', 'Ralston', 15.879999999999999)]

## Joins and Arithmetic Operations

> **QUESTION 11**: Write a SQL query to show the total number of albums and the average number of tracks per album for every artist. The result should include the artist ID, artist's name, total albums (name the column "Albums") and average tracks per album (name the column "TracksPerAlbum"). Sort the results in alphabetical order of artist name. 
> 

In [74]:
%%sql

select album.artistid, artist.name,
    COUNT(DISTINCT album.albumid) as `Albums`,
    count(DISTINCT track.trackid)/count(DISTINCT track.albumid) as `Tracks Per Album`
    from track join album on track.albumid = album.albumid
    join artist on album.artistid = artist.artistid
    group by album.artistid order by artist.name ;

 * sqlite:///chinook.sqlite
Done.


[(1, 'AC/DC', 2, 9),
 (230, 'Aaron Copland & London Symphony Orchestra', 1, 1),
 (202, 'Aaron Goldberg', 1, 1),
 (214, 'Academy of St. Martin in the Fields & Sir Neville Marriner', 1, 2),
 (215, 'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner', 1, 1),
 (222, 'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair', 1, 1),
 (257, 'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart', 1, 1),
 (2, 'Accept', 2, 2),
 (260, 'Adrian Leaper & Doreen de Feis', 1, 1),
 (3, 'Aerosmith', 1, 15),
 (197, 'Aisha Duo', 1, 2),
 (4, 'Alanis Morissette', 1, 13),
 (206, 'Alberto Turco & Nova Schola Gregoriana', 1, 1),
 (5, 'Alice In Chains', 1, 12),
 (252, 'Amy Winehouse', 2, 11),
 (209, 'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker', 1, 1),
 (243, 'Antal Doráti & London Symphony Orchestra', 1, 1),
 (6, 'Antônio Carlos Jobim', 2, 15),
 (7, 'Apocalyptica', 1, 8),
 (159, 'Aquaman', 1, 1),
 (8, 'Audioslave', 3, 13),
 (9, 'BackBeat', 1, 12),
 (224, 'Barry Wordsworth & BBC Concert Orchestra', 1, 1),
 (147, 'Battlestar Galactica', 2, 10),
 (158, 'Battlestar Galactica (Classic)', 1, 24),
 (237, 'Berliner Philharmoniker & Hans Rosbaud', 1, 1),
 (248, 'Berliner Philharmoniker & Herbert Von Karajan', 3, 1),
 (216, 'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer', 1, 1),
 (10, 'Billy Cobham', 1, 8),
 (11, 'Black Label Society', 2, 9),
 (12, 'Black Sabbath', 2, 8),
 (13, 'Body Count', 1, 17),
 (229, 'Boston Symphony Orchestra & Seiji Ozawa', 1, 1),
 (219, 'Britten Sinfonia, Ivor Bolton & Lesley Garrett', 1, 1),
 (14, 'Bruce Dickinson', 1, 11),
 (15, 'Buddy Guy', 1, 11),
 (273, 'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu', 1, 1),
 (16, 'Caetano Veloso', 2, 10),
 (196, 'Cake', 1, 1),
 (253, 'Calexico', 1, 1),
 (262, "Charles Dutoit & L'Orchestre Symphonique de Montréal", 1, 1),
 (220, 'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti', 1, 1),
 (233, 'Chicago Symphony Orchestra & Fritz Reiner', 1, 1),
 (17, 'Chico Buarque', 1, 34),
 (18, 'Chico Science & Nação Zumbi', 2, 18),
 (244, 'Choir Of Westminster Abbey & Simon Preston', 1, 1),
 (246, 'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker', 1, 1),
 (205, 'Chris Cornell', 1, 14),
 (250, "Christopher O'Riley", 1, 1),
 (19, 'Cidade Negra', 2, 15),
 (20, 'Cláudio Zoli', 1, 10),
 (76, 'Creedence Clearwater Revival', 2, 20),
 (77, 'Cássia Eller', 2, 15),
 (55, 'David Coverdale', 1, 12),
 (58, 'Deep Purple', 11, 8),
 (78, 'Def Leppard', 1, 16),
 (79, 'Dennis Chambers', 1, 9),
 (80, 'Djavan', 2, 13),
 (157, 'Dread Zeppelin', 1, 1),
 (37, 'Ed Motta', 1, 14),
 (242, 'Edo de Waart & San Francisco Symphony', 1, 1),
 (41, 'Elis Regina', 1, 14),
 (235, 'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra', 1, 1),
 (272, 'Emerson String Quartet', 1, 1),
 (208, 'English Concert & Trevor Pinnock', 2, 1),
 (263, 'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir', 1, 1),
 (81, 'Eric Clapton', 2, 24),
 (226, 'Eugene Ormandy', 3, 1),
 (82, 'Faith No More', 4, 13),
 (83, 'Falamansa', 1, 14),
 (241, 'Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos', 1, 1),
 (84, 'Foo Fighters', 4, 11),
 (85, 'Frank Sinatra', 1, 24),
 (23, 'Frank Zappa & Captain Beefheart', 1, 9),
 (251, 'Fretwork', 1, 1),
 (86, 'Funk Como Le Gusta', 1, 16),
 (69, 'Gene Krupa', 1, 22),
 (270, 'Gerald Moore', 1, 1),
 (27, 'Gilberto Gil', 3, 10),
 (87, 'Godsmack', 1, 12),
 (56, 'Gonzaguinha', 1, 14),
 (54, 'Green Day', 2, 17),
 (88, "Guns N' Roses", 3, 14),
 (240, 'Gustav Mahler', 1, 1),
 (267, 'Göteborgs Symfoniker & Neeme Järvi', 1, 1),
 (198, 'Habib Koité and Bamada', 1, 2),
 (225, 'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker', 1, 1),
 (148, 'Heroes', 1, 23),
 (210, 'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer', 1, 1),
 (180, 'House Of Pain', 1, 19),
 (89, 'Incognito', 1, 13

> **QUESTION 12**:  Write a SQL query to display the top 10 highest grossing tracks in 2012. The result should contain the track ID, track name, number of units sold, and the total revenue from the track in 2012.

In [86]:
%%sql
select invoiceline.trackid,track.name,
    (select sum(quantity) where strftime('%Y',invoicedate) = "2012") as `Units Sold`,
    (select sum(total) where strftime('%Y',invoicedate) = "2012") as `Revenue`
    from invoiceline JOIN track on invoiceline.trackid = track.trackid
    JOIN invoice on invoiceline.invoiceid = invoice.invoiceid
    group by invoiceline.trackid,track.name order by `Revenue` DESC LIMIT 10 ;

 * sqlite:///chinook.sqlite
Done.


[(2945, 'Peace On Earth', 2, 24.849999999999998),
 (2837, 'Crossroads, Pt. 1', 1, 23.86),
 (2846, 'Seven Minutes to Midnight', 1, 23.86),
 (2855, 'Company Man', 1, 23.86),
 (2864, 'Orientation', 1, 23.86),
 (2873, 'House of the Rising Sun', 1, 23.86),
 (2882, 'Lost Survival Guide', 1, 23.86),
 (2891, 'Enter 77', 1, 23.86),
 (2900, 'Exposé', 1, 23.86),
 (2909, 'Catch-22', 1, 23.86)]

## Joining Multiple Tables

> **QUESTION 13**: Show the following information for all the tracks by the Artist "Metallica": Track ID, Track Name, Album Title, Artist Name, Composer, Media Type, Genre and track length in milliseconds. Order the tracks in alphabetical order of album names.
> 

In [89]:
%%sql

SELECT trackid as `TrackId`,
    track.name as `Track`,
    album.title as `Album`, 
    artist.name as `Artist`,
    composer,
    mediatype.name as `MediaType`,
    genre.name as `Genre`,
    milliseconds
    from track join album on track.albumid = album.albumid
    join artist on album.artistid = artist.artistid
    join mediatype on track.mediatypeid = mediatype.mediatypeid
    join genre on track.genreid = genre.genreid
    where artist.name = "Metallica" ORDER BY `album`;

 * sqlite:///chinook.sqlite
Done.


[(1893, 'Blackened', '...And Justice For All', 'Metallica', 'James Hetfield, Lars Ulrich & Jason Newsted', 'MPEG audio file', 'Metal', 403382),
 (1894, '...And Justice For All', '...And Justice For All', 'Metallica', 'James Hetfield, Lars Ulrich & Kirk Hammett', 'MPEG audio file', 'Metal', 585769),
 (1895, 'Eye Of The Beholder', '...And Justice For All', 'Metallica', 'James Hetfield, Lars Ulrich & Kirk Hammett', 'MPEG audio file', 'Metal', 385828),
 (1896, 'One', '...And Justice For All', 'Metallica', 'James Hetfield & Lars Ulrich', 'MPEG audio file', 'Metal', 446484),
 (1897, 'The Shortest Straw', '...And Justice For All', 'Metallica', 'James Hetfield and Lars Ulrich', 'MPEG audio file', 'Metal', 395389),
 (1898, 'Harvester Of Sorrow', '...And Justice For All', 'Metallica', 'James Hetfield and Lars Ulrich', 'MPEG audio file', 'Metal', 345547),
 (1899, 'The Frayed Ends Of Sanity', '...And Justice For All', 'Metallica', 'James Hetfield, Lars Ulrich and Kirk Hammett', 'MPEG audio file', 'Metal', 464039),
 (1900, 'To Live Is To Die', '...And Justice For All', 'Metallica', 'James Hetfield, Lars Ulrich and Cliff Burton', 'MPEG audio file', 'Metal', 588564),
 (1901, 'Dyers Eve', '...And Justice For All', 'Metallica', 'James Hetfield, Lars Ulrich and Kirk Hammett', 'MPEG audio file', 'Metal', 313991),
 (1801, 'Enter Sandman', 'Black Album', 'Metallica', 'James Hetfield, Lars Ulrich and Kirk Hammett', 'MPEG audio file', 'Metal', 332251),
 (1802, 'Sad But True', 'Black Album', 'Metallica', 'Ulrich', 'MPEG audio file', 'Metal', 324754),
 (1803, 'Holier Than Thou', 'Black Album', 'Metallica', 'Ulrich', 'MPEG audio file', 'Metal', 227892),
 (1804, 'The Unforgiven', 'Black Album', 'Metallica', 'James Hetfield, Lars Ulrich and Kirk Hammett', 'MPEG audio file', 'Metal', 387082),
 (1805, 'Wherever I May Roam', 'Black Album', 'Metallica', 'Ulrich', 'MPEG audio file', 'Metal', 404323),
 (1806, "Don't Tread On Me", 'Black Album', 'Metallica', 'Ulrich', 'MPEG audio file', 'Metal', 240483),
 (1807, 'Through The Never', 'Black Album', 'Metallica', 'James Hetfield, Lars Ulrich and Kirk Hammett', 'MPEG audio file', 'Metal', 244375),
 (1808, 'Nothing Else Matters', 'Black Album', 'Metallica', 'Ulrich', 'MPEG audio file', 'Metal', 388832),
 (1809, 'Of Wolf And Man', 'Black Album', 'Metallica', 'James Hetfield, Lars Ulrich and Kirk Hammett', 'MPEG audio file', 'Metal', 256835),
 (1810, 'The God That Failed', 'Black Album', 'Metallica', 'Ulrich', 'MPEG audio file', 'Metal', 308610),
 (1811, 'My Friend Of Misery', 'Black Album', 'Metallica', 'James Hetfield, Lars Ulrich and Jason Newsted', 'MPEG audio file', 'Metal', 409547),
 (1812, 'The Struggle Within', 'Black Album', 'Metallica', 'Ulrich', 'MPEG audio file', 'Metal', 234240),
 (408, 'Free Speech For The Dumb', 'Garage Inc. (Disc 1)', 'Metallica', 'Molaney/Morris/Roberts/Wainwright', 'MPEG audio file', 'Metal', 155428),
 (409, "It's Electric", 'Garage Inc. (Disc 1)', 'Metallica', 'Harris/Tatler', 'MPEG audio file', 'Metal', 213995),
 (410, 'Sabbra Cadabra', 'Garage Inc. (Disc 1)', 'Metallica', 'Black Sabbath', 'MPEG audio file', 'Metal', 380342),
 (411, 'Turn The Page', 'Garage Inc. (Disc 1)', 'Metallica', 'Seger', 'MPEG audio file', 'Metal', 366524),
 (412, 'Die Die My Darling', 'Garage Inc. (Disc 1)', 'Metallica', 'Danzig', 'MPEG audio file', 'Metal', 149315),
 (413, 'Loverman', 'Garage Inc. (Disc 1)', 'Metallica', 'Cave', 'MPEG audio file', 'Metal', 472764),
 (414, 'Mercyful Fate', 'Garage Inc. (Disc 1)', 'Metallica', 'Diamond/Shermann', 'MPEG audio file', 'Metal', 671712),
 (415, 'Astronomy', 'Garage Inc. (Disc 1)', 'Metallica', 'A.Bouchard/J.Bouchard/S.Pearlman', 'MPEG audio file', 'Metal', 397531),
 (416, 'Whiskey In The Jar', 'Garage Inc. (Disc 1)', 'Metallica', 'Traditional', 'MPEG audio file', 'Metal', 305005),
 (417, "Tuesday's Gone", 'Garage Inc. (Disc 1)', 'Metallica', 'Collins/Van Zandt', 'MPEG audio file', 'Metal', 545750),
 (418, 'The More I See', 'Garage Inc. (Disc 1)', 'Metallica', 'Mo

> **QUESTION 14**:  Modify the above query to include the total revenue from the sales of each track.

In [94]:
%%sql
SELECT track.trackid as `Track ID`,
    track.name as `Track`,
    album.title as `Album`, 
    artist.name as `Artist`,
    composer,
    mediatype.name as `MediaType`,
    genre.name as `Genre`,
    invoice.total as `Revenue`
    from track join album on track.albumid = album.albumid
    join artist on album.artistid = artist.artistid
    join mediatype on track.mediatypeid = mediatype.mediatypeid
    join genre on track.genreid = genre.genreid
    join invoiceline on track.trackid = invoiceline.trackid
    join invoice on invoiceline.invoiceid =invoice.invoiceid
    where artist.name = "Metallica" ORDER BY `Revenue` DESC;

 * sqlite:///chinook.sqlite
Done.


[(412, 'Die Die My Darling', 'Garage Inc. (Disc 1)', 'Metallica', 'Danzig', 'MPEG audio file', 'Metal', 13.86),
 (1804, 'The Unforgiven', 'Black Album', 'Metallica', 'James Hetfield, Lars Ulrich and Kirk Hammett', 'MPEG audio file', 'Metal', 13.86),
 (1813, 'Helpless', 'Garage Inc. (Disc 2)', 'Metallica', 'Harris/Tatler', 'MPEG audio file', 'Metal', 13.86),
 (1822, 'Stone Cold Crazy', 'Garage Inc. (Disc 2)', 'Metallica', 'Deacon/May/Mercury/Taylor', 'MPEG audio file', 'Metal', 13.86),
 (1831, 'Motorbreath', "Kill 'Em All", 'Metallica', 'James Hetfield', 'MPEG audio file', 'Metal', 13.86),
 (1840, '2 X 4', 'Load', 'Metallica', 'James Hetfield, Lars Ulrich, Kirk Hammett', 'MPEG audio file', 'Metal', 13.86),
 (416, 'Whiskey In The Jar', 'Garage Inc. (Disc 1)', 'Metallica', 'Traditional', 'MPEG audio file', 'Metal', 13.86),
 (1808, 'Nothing Else Matters', 'Black Album', 'Metallica', 'Ulrich', 'MPEG audio file', 'Metal', 13.86),
 (1817, 'Last Caress/Green Hell', 'Garage Inc. (Disc 2)', 'Metallica', 'Danzig', 'MPEG audio file', 'Metal', 13.86),
 (1886, 'Invisible Kid', 'St. Anger', 'Metallica', 'Bob Rock/James Hetfield/Kirk Hammett/Lars Ulrich', 'MPEG audio file', 'Metal', 13.86),
 (1895, 'Eye Of The Beholder', '...And Justice For All', 'Metallica', 'James Hetfield, Lars Ulrich & Kirk Hammett', 'MPEG audio file', 'Metal', 13.86),
 (1898, 'Harvester Of Sorrow', '...And Justice For All', 'Metallica', 'James Hetfield and Lars Ulrich', 'MPEG audio file', 'Metal', 8.91),
 (1875, 'Ride The Lightning', 'Ride The Lightning', 'Metallica', 'Metallica', 'MPEG audio file', 'Metal', 8.91),
 (1881, 'The Call Of Ktulu', 'Ride The Lightning', 'Metallica', 'Metallica', 'MPEG audio file', 'Metal', 8.91),
 (1887, 'My World', 'St. Anger', 'Metallica', 'Bob Rock/James Hetfield/Kirk Hammett/Lars Ulrich', 'MPEG audio file', 'Metal', 8.91),
 (1893, 'Blackened', '...And Justice For All', 'Metallica', 'James Hetfield, Lars Ulrich & Jason Newsted', 'MPEG audio file', 'Metal', 8.91),
 (1899, 'The Frayed Ends Of Sanity', '...And Justice For All', 'Metallica', 'James Hetfield, Lars Ulrich and Kirk Hammett', 'MPEG audio file', 'Metal', 8.91),
 (1852, 'The Outlaw Torn', 'Load', 'Metallica', 'James Hetfield, Lars Ulrich', 'MPEG audio file', 'Metal', 8.91),
 (1858, 'Leper Messiah', 'Master Of Puppets', 'Metallica', 'C.Burton', 'MPEG audio file', 'Metal', 8.91),
 (1864, 'The Unforgiven II', 'ReLoad', 'Metallica', 'Hetfield, Ulrich, Hammett', 'MPEG audio file', 'Metal', 8.91),
 (1870, 'Prince Charming', 'ReLoad', 'Metallica', 'Hetfield, Ulrich', 'MPEG audio file', 'Metal', 8.91),
 (1876, 'For Whom The Bell Tolls', 'Ride The Lightning', 'Metallica', 'Metallica', 'MPEG audio file', 'Metal', 8.91),
 (1882, 'Frantic', 'St. Anger', 'Metallica', 'Bob Rock/James Hetfield/Kirk Hammett/Lars Ulrich', 'MPEG audio file', 'Metal', 8.91),
 (1888, 'Shoot Me Again', 'St. Anger', 'Metallica', 'Bob Rock/James Hetfield/Kirk Hammett/Lars Ulrich', 'MPEG audio file', 'Metal', 8.91),
 (1894, '...And Justice For All', '...And Justice For All', 'Metallica', 'James Hetfield, Lars Ulrich & Kirk Hammett', 'MPEG audio file', 'Metal', 8.91),
 (1900, 'To Live Is To Die', '...And Justice For All', 'Metallica', 'James Hetfield, Lars Ulrich and Cliff Burton', 'MPEG audio file', 'Metal', 8.91),
 (1829, 'Hit The Lights', "Kill 'Em All", 'Metallica', 'James Hetfield, Lars Ulrich', 'MPEG audio file', 'Metal', 8.91),
 (1835, 'Phantom Lord', "Kill 'Em All", 'Metallica', 'James Hetfield, Lars Ulrich, Dave Mustaine', 'MPEG audio file', 'Metal', 8.91),
 (1841, 'The House Jack Built', 'Load', 'Metallica', 'James Hetfield, Lars Ulrich, Kirk Hammett', 'MPEG audio file', 'Metal', 8.91),
 (1847, 'Poor Twisted Me', 'Load', 'Metallica', 'James Hetfield, Lars Ulrich', 'MPEG audio file', 'Metal', 8.91),
 (1853, 'Battery', 'Master Of Puppets', 'Metallica', 'J.Hetfield/L.Ulrich', 'MPEG audio file', 'Metal', 8.91),
 (1859, 'Orion', 'Master Of Puppets', 'Metallica', 'K.Hammett', 'MPEG audio file', 'Metal', 8.91),
 (1865, '

Let's save our work before continuing.

## Table Creation  and Foreign Keys

> **QUESTION 15**: Create a new table `HallOfFame` to track the list of artists who have been added into the Chinook Hall of Fame. The table should contain three columns: 
>
> 1. `HallOfFameId` (int): Primary key with [Auto Increment](https://www.sqlite.org/autoinc.html)
> 2. `ArtistId` (int): Foreign key (from the Artist table)
> 3. `YearAdded` (int): The year the artist was added to the hall of fame 
>
> Once created, add 5 entries to the table (any artists of your choice).

In [96]:
%%sql

CREATE TABLE HallofFame (HallofFameID INTEGER PRIMARY KEY AUTOINCREMENT ,
                        ArtistID INTEGER NOT NULL,
                        YearAdded INTEGER,
                        FOREIGN KEY(`ArtistId`) REFERENCES 
                        Artist(`artistid`));

 * sqlite:///chinook.sqlite
Done.


[]

In [97]:
%%sql

INSERT INTO HallofFame (ArtistId,YearAdded) VALUES ("56","2018") ;

 * sqlite:///chinook.sqlite
1 rows affected.


[]

In [98]:
%%sql 
INSERT INTO HallofFame (ArtistId,YearAdded) VALUES ("92","2018") ;
INSERT INTO HallofFame (ArtistId,YearAdded) VALUES ("94","2018") ;
INSERT INTO HallofFame (ArtistId,YearAdded) VALUES ("45","2018") ;
INSERT INTO HallofFame (ArtistId,YearAdded) VALUES ("96","2018") ;

 * sqlite:///chinook.sqlite
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.


[]

Once the table is created and records have been inserted, you can view the list of artists in the hall of fame using the following query.

In [99]:
%%sql

SELECT * FROM HallOfFame JOIN Artist ON HallOfFame.ArtistId=Artist.ArtistId

 * sqlite:///chinook.sqlite
Done.


[(1, 56, 2018, 56, 'Gonzaguinha'),
 (2, 92, 2018, 92, 'Jamiroquai'),
 (3, 94, 2018, 94, 'Jimi Hendrix'),
 (4, 45, 2018, 45, 'Sandra De Sá'),
 (5, 96, 2018, 96, 'Jota Quest')]

## Inserting Data into Tables

> **QUESTION 16**: Write SQL queries to insert the following records into the database:
> 
> 1. A new artist called "Linkin Park"
> 2. Two new albums for the artist Linkin Park:
>     1. Hybrid Theory
>     2. Meteora
> 3. Six new tracks (come up with sensible values for columns like Composer, Milliseconds etc.):
>     1. Papercut (in the album Hybrid Theory)
>     2. In The End (in the album Hybrid Theory)
>     3. Crawling (in the album Hybrid Theory)
>     4. Somewhere I Belong (in the album Meteora)
>     5. Numb (in the album Meteora)
>     6. Breaking the Habit (in the album Meteora)

Here's the query to insert a new artist:

In [101]:
%%sql

INSERT INTO Artist (Name) VALUES ("Linkin Park") ;

 * sqlite:///chinook.sqlite
1 rows affected.


[]

We write the query to insert the new albums below:

In [102]:
%%sql

INSERT INTO Album("Title","ArtistId") VALUES ("Hybrid Theory", "276") ;

 * sqlite:///chinook.sqlite
1 rows affected.


[]

In [103]:
%%sql
INSERT INTO Album("Title","ArtistId") VALUES ("Meteora", "276") ;

 * sqlite:///chinook.sqlite
1 rows affected.


[]

In [105]:
%%sql
select * from album ORDER BY Albumid DESC LIMIT 10  ;

 * sqlite:///chinook.sqlite
Done.


[(349, 'Meteora', 276),
 (348, 'Hybrid Theory', 276),
 (347, 'Koyaanisqatsi (Soundtrack from the Motion Picture)', 275),
 (346, 'Mozart: Chamber Music', 274),
 (345, "Monteverdi: L'Orfeo", 273),
 (344, "Schubert: The Late String Quartets & String Quintet (3 CD's)", 272),
 (343, 'Respighi:Pines of Rome', 226),
 (342, 'Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3', 271),
 (341, 'Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder', 270),
 (340, "Liszt - 12 Études D'Execution Transcendante", 269)]

As we can see, two new Albums with the `AlbumID`- 348 and 349 are now created.

Now, we will write the query to insert the new tracks below:

In [106]:
%%sql 
INSERT INTO Track(`name`,`albumid`,mediatypeid,genreid,`composer`,`milliseconds`,`bytes`,`unitprice`) VALUES ("Papercut","348","MPEG audio file","metal","composer1","222333","2342","12") ;

 * sqlite:///chinook.sqlite
1 rows affected.


[]

In [107]:
%%sql 
INSERT INTO Track(`name`,`albumid`,mediatypeid,genreid,`composer`,`milliseconds`,`bytes`,`unitprice`) VALUES ("In The End","348","MPEG audio file","metal","composer1","222333","33441","12") ;
INSERT INTO Track(`name`,`albumid`,mediatypeid,genreid,`composer`,`milliseconds`,`bytes`,`unitprice`) VALUES ("Crawling","348","MPEG audio file","metal","composer1","222333","44554","2") ;
INSERT INTO Track(`name`,`albumid`,mediatypeid,genreid,`composer`,`milliseconds`,`bytes`,`unitprice`) VALUES ("Somewhere I Belong","349","MPEG audio file","metal","composer1","346333","2342","11") ;
INSERT INTO Track(`name`,`albumid`,mediatypeid,genreid,`composer`,`milliseconds`,`bytes`,`unitprice`) VALUES ("Breaking the Habit","349","MPEG audio file","metal","composer1","26633","2342","5") ;
INSERT INTO Track(`name`,`albumid`,mediatypeid,genreid,`composer`,`milliseconds`,`bytes`,`unitprice`) VALUES ("Numb","349","MPEG audio file","metal","composer1","222333","2342","3") ;

 * sqlite:///chinook.sqlite
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.


[]

##### Let us look at all the entries that we have made.

In [108]:
%%sql

SELECT * FROM Artist WHERE Name="Linkin Park"

 * sqlite:///chinook.sqlite
Done.


[(276, 'Linkin Park')]

In [109]:
%%sql

SELECT * FROM Album JOIN Artist on Album.ArtistId=Artist.ArtistId WHERE Artist.Name="Linkin Park"

 * sqlite:///chinook.sqlite
Done.


[(348, 'Hybrid Theory', 276, 276, 'Linkin Park'),
 (349, 'Meteora', 276, 276, 'Linkin Park')]

In [110]:
%%sql

SELECT * 
    FROM Track JOIN Album
    ON Track.AlbumId=Album.AlbumId
    JOIN Artist
    ON Album.ArtistId=Artist.ArtistId 
    WHERE Artist.Name="Linkin Park"

 * sqlite:///chinook.sqlite
Done.


[(3504, 'Papercut', 348, 'MPEG audio file', 'metal', 'composer1', 222333, 2342, 12, 348, 'Hybrid Theory', 276, 276, 'Linkin Park'),
 (3505, 'In The End', 348, 'MPEG audio file', 'metal', 'composer1', 222333, 33441, 12, 348, 'Hybrid Theory', 276, 276, 'Linkin Park'),
 (3506, 'Crawling', 348, 'MPEG audio file', 'metal', 'composer1', 222333, 44554, 2, 348, 'Hybrid Theory', 276, 276, 'Linkin Park'),
 (3507, 'Somewhere I Belong', 349, 'MPEG audio file', 'metal', 'composer1', 346333, 2342, 11, 349, 'Meteora', 276, 276, 'Linkin Park'),
 (3508, 'Breaking the Habit', 349, 'MPEG audio file', 'metal', 'composer1', 26633, 2342, 5, 349, 'Meteora', 276, 276, 'Linkin Park'),
 (3509, 'Numb', 349, 'MPEG audio file', 'metal', 'composer1', 222333, 2342, 3, 349, 'Meteora', 276, 276, 'Linkin Park')]

## Summary

In this mini project, we could see the basics of SQL and how to apply them to the datasets to answer some questions.

In the real world scenario, the datasets can have millions and billions of rows and that is when we are able to utilize the true power of SQL. The answers that we get from the data are then applied for data analysis and visualised to find out certain patterns and take actions .